name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: building
      run: |
        npm install yarn gulp-cli
        which gulp
        yarn install
        gulp build
